version: '3'

services:
  ########################
  ########## api #########
  ########################
  mutant_service:
    build: .
    container_name: mutant_service
    restart: always
    expose:
      - "5000"
    environment:
      - API_PORT=5000

      - POSTGRES_HOST=mutant_postgres
      - POSTGRES_DB=mutantApp
      - POSTGRES_USER=admin
      - POSTGRES_PWD=admin
      - POSTGRES_PORT=5432

      - VIRTUAL_PORT=5000
      - VIRTUAL_PATH=/
      - VIRTUAL_DEST=/
      - VIRTUAL_HOST=api.francisco-calixto.com
  
  ########################
  ########## db ##########
  ########################
  mutant_postgres:
    image: arm64v8/postgres:latest
    container_name: mutant_postgres
    restart: always
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=mutantApp
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: mutantApp-nginx-proxy
    ports:
      - "83:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - HTTP_PORT=80

  ########################
  ####### adminer ########
  ########################
  mutant_postgres_adminer:
      image: arm32v7/adminer:latest
      restart: always
      container_name: mutant_postgres_adminer
      ports:
        - 8888:8080
      environment:
        - ADMINER_DESIGN=nette
        - ADMINER_DEFAULT_SERVER=postgres